spring.application.name=dbme

sendgrid.api-key=
sendgrid.email=

public.api.base-url=http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList
public.api.service-key=

spring.jwt.secret=efjeoapwgj5e6eajpgepjg8894e6Agrionawoidfjeoifag31awhoefeofja4aega45agrlkagjaejiognvlbnaio3je

# postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5400/dbme
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# for development
spring.batch.jdbc.initialize-schema=always

# redis
spring.redis.host=localhost
spring.redis.port=6300